host: localhost
port: 4000
baseurl: /notoma
permalink: /:categories/:title

# Aux links for the upper right navigation
aux_links:
  "Notoma on Gibhub":
    - "//github.com/xnutsive/notoma"

# Footer content appears at the bottom of every page's main content
footer_content: |
  Copyright &copy; 2020 Nate Gadzibalaev. Distributed by an <a href=\"https://github.com/pmarsceill/just-the-docs/tree/master/LICENSE.txt\">Apache 2 license.</a>

ga_tracking: UA-17294800-4

exclude:
  - .idea/
  - .gitignore
  - vendor

remote_theme: pmarsceill/just-the-docs
theme: "just-the-docs"

highlighter: rouge
markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
 parse_block_html: true
